houston_fitness = {
    "query": {
        "total": 23,
        "page": 1,
        "per_page": 20,
        "query": "fitness",
        "location": {
            "latitude": 29.7604,
            "longitude": -95.3698
        },
        "radius": 50,
        "online": null,
        "category_slugs": null,
        "provider_slugs": null,
        "updated_after": null,
        "order": null
    },
    "deals": [
        {
            "deal": {
                "id": 1077405,
                "title": "Five Dance-Fitness Classes at The Stiletto Fitness Experience (45% Off)",
                "short_title": "45% Off Dance-Fitness Classes",
                "description": "Five Dance-Fitness Classes",
                "fine_print": "Limit 2 per person, may buy 2 additional as gift(s). Limit 1 per visit.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1077405/click?api_key=WkXDXfXX",
                "price": 44,
                "value": 80,
                "discount_amount": 36,
                "discount_percentage": 0.45,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1077405/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-05-02T00:00:00Z",
                "created_at": "2019-01-02T09:18:29Z",
                "updated_at": "2019-01-02T09:18:29Z",
                "merchant": {
                    "id": 315829,
                    "name": "The Stiletto Fitness Experience",
                    "address": "3300 Chimney Rock Road",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77056",
                    "country": "US",
                    "latitude": 29.729801,
                    "longitude": -95.47732099999999
                }
            }
        },
        {
            "deal": {
                "id": 1187594,
                "title": "One- or Two-Month Gym Membership with Fitness Consultation and Personal-Training Session at Snap Fitness (Up to 96% Off)",
                "short_title": "Up to 96% Off Gym Membership to Snap Fitness",
                "description": "A good workout regimen provides the courage needed to march back into the office, take the clown nose off, and demand a smaller, funnier car. Fill oversize shoes with self-confidence with this voucher. Choose Between Two Options $8 for a one-month gym membership with a fitness consultation and one personal-training session (a $184.95 value) $19.50 for a two-month gym membership with a fitness consultation and one personal-training session (a $219.90 value) Snap Fitness facilitates workouts 24 hours a day with a repertoire of Cybex treadmills, weight machines, and free weights. Each membership begins with a personal-training session, during which a skilled fitness instructor conducts an assessment that includes BMI monitoring and suggestions for a weight-loss plan that doesn’t include bribing gravity.",
                "fine_print": "Must activate at Pearland location by expiration date on your voucher. Under 18 requires parent or legal guardian consent. Must sign waiver. Limit 1 per person, may buy 1 additional as gift(s). New customers only. Valid only for option purchased. Must be 18 or older.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1187594/click?api_key=WkXDXfXX",
                "price": 19.5,
                "value": 219.9,
                "discount_amount": 200.4,
                "discount_percentage": 0.9113233287858117,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1187594/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-06-20T00:00:00Z",
                "created_at": "2019-02-20T09:31:14Z",
                "updated_at": "2019-02-20T09:31:14Z",
                "merchant": {
                    "id": 290285,
                    "name": "Snap Fitness",
                    "address": "3108 Dixie Farm Rd.",
                    "locality": "Pearland",
                    "region": "TX",
                    "postal_code": "77581",
                    "country": "US",
                    "latitude": 29.5484422,
                    "longitude": -95.2317125,
                    "phone_number": "+12819969800"
                }
            }
        },
        {
            "deal": {
                "id": 970067,
                "title": "Fitness Boxing or Personal Training at Premier Boxing for Fitness (Up to 90% Off). Six Options Available.",
                "short_title": "Up to 90% Off Fitness Classes at Premier Boxing for Fitness",
                "description": "The classes are tailored to one’s individual abilities and promote a healthy lifestyle as well as reduce stress levels Classes are designed for participants of all experience levels View the class schedule Two classes scheduled for adult and youth. Premier Boxing for Fitness At Premier Boxing for Fitness, certified instructors are focused on promoting a healthy lifestyle. They guide students of all experience levels, from beginners to advanced practitioners, through various fitness classes helping them stay in shape and achieve their fitness goals. Patrons can also count on one-on-one personal training sessions that are tailored to each customer separately. Instructors keep clients satisfied and motivated because they know that only through hard work can anyone get desired fitness results. Here, classes are as fun as they are challenging.",
                "fine_print": "5-class pass must be used within 30 days from first class use. 10-class pass must be used within 45 days from first class use. Kids ages 8-17 must be accompanied by a parent or guardian to all classes. Reservation required. May redeem across visits. Subject to availability. Must sign waiver. Limit 1 per person, may buy 3 additional as gift(s). Limit 1 per visit. Valid only for option purchased. Not valid for clients active within the past 6 month(s). All goods or services must be used by the same person.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/970067/click?api_key=WkXDXfXX",
                "price": 19,
                "value": 200,
                "discount_amount": 181,
                "discount_percentage": 0.905,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/970067/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-03-09T00:00:00Z",
                "created_at": "2018-11-09T09:17:16Z",
                "updated_at": "2018-11-09T09:17:16Z",
                "merchant": {
                    "id": 296987,
                    "name": "Premier Boxing for Fitness",
                    "address": "510 Wisconsin Street",
                    "locality": "South Houston",
                    "region": "TX",
                    "postal_code": "77587",
                    "country": "US",
                    "latitude": 29.6568881,
                    "longitude": -95.231011
                }
            }
        },
        {
            "deal": {
                "id": 1033109,
                "title": "5-Class Pass for Boxing Fit or White Collar Boxing Class at Slava Boxing Gym & Heights Fitness (Up to 81% Off)",
                "short_title": "Up to 81% Off Classes at Slava Boxing Gym & Heights Fitness",
                "description": "White Collar Boxing classes emphasize boxing techniques and physical conditioning by training like a boxer without the actual competition. The diverse elements of this training program can be tailored to fit each client’s needs. Boxing Fit sessions incorporate basic boxing movements into a challenging workout that helps participants burn calories and tone their bodies. View the class schedule",
                "fine_print": "Once activated, 5 classes must be used within 1 month. All goods or services must be used by the same person. Registration required. Must sign waiver. Limit 2 per person, may buy 2 additional as gift(s). May be repurchased every 180 days. Valid only for option purchased.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1033109/click?api_key=WkXDXfXX",
                "price": 29,
                "value": 100,
                "discount_amount": 71,
                "discount_percentage": 0.71,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Activities & Events",
                "category_slug": "activities-events",
                "image_url": "https://api.discountapi.com/v2/deals/1033109/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-03-07T00:00:00Z",
                "created_at": "2018-12-07T09:22:49Z",
                "updated_at": "2019-01-12T09:53:20Z",
                "merchant": {
                    "id": 305392,
                    "name": "Slava Boxing Gym & Heights Fitness",
                    "address": "1215 W 20th St",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77008",
                    "country": "US",
                    "latitude": 29.804101,
                    "longitude": -95.420329,
                    "phone_number": "+12817170642"
                }
            }
        },
        {
            "deal": {
                "id": 1172841,
                "title": "3 Weeks of Unlimited Boot-Camp Sessions or 5 Weeks Plus a Fitness E-Book at Fit Body Boot Camp (Up to 80% Off) ",
                "short_title": "Up to 80% Off at Fit Body Boot Camp ",
                "description": "With this voucher, clients can attend any sessions that are available during the three- or five-week period. Sessions are subject to availability and calendars will vary by location. Choose Between Two Options Three weeks of unlimited fitness boot-camp sessions (a $185.25 value) Five weeks of unlimited fitness boot-camp sessions, plus a fitness e-book (a $337.75 value) Both options include access to unlimited boot-camp sessions for the duration of the program and nutritional guidance. The sessions combine cardio training with resistance and weight work, helping to maximize caloric burn both during and after the workout. Click here for a list of frequently asked questions. Orientation booking hours for Spring and Woodland locations are 9 a.m. to 7 p.m.",
                "fine_print": "Classes subject to availability. Walk-ins not accepted. Classes must be used by the same person. Must use all visits at the same chosen location. Must be 18 or older or have parental consent. Online reservation required. Must sign waiver. Limit 1 per person, may buy 1 additional as gift(s). Valid only for option purchased. Not valid for clients active within the past 6 month(s). Valid only at listed locations.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1172841/click?api_key=WkXDXfXX",
                "price": 49,
                "value": 185.25,
                "discount_amount": 136.25,
                "discount_percentage": 0.7354925775978407,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1172841/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-05-16T00:00:00Z",
                "created_at": "2019-02-15T09:42:30Z",
                "updated_at": "2019-02-15T09:42:30Z",
                "merchant": {
                    "id": 332692,
                    "name": "Fit Body Boot Camp",
                    "address": "727 East Louetta Road",
                    "locality": "Spring",
                    "region": "TX",
                    "postal_code": "77373",
                    "country": "US",
                    "latitude": 30.0725165,
                    "longitude": -95.4241284,
                    "phone_number": "+18326550303"
                }
            }
        },
        {
            "deal": {
                "id": 1041264,
                "title": "Five or Ten Zumba Classes or One Month of Unlimited Zumba Classes at Goza Dance Fitness (Up to 51% Off)",
                "short_title": "Up to 51% Off Zumba Classes at Goza Dance Fitness",
                "description": "Choice of: Five Zumba Classes Ten Zumba Classes One Month of Unlimited Zumba Classes Zumba: A Fitness Style on the Move Zumba is one of the peppiest fitness options on the schedule. Read on to learn a little about where it comes from. Because of its tendency to dissolve inhibitions by the time the beat sets in, Zumba has been deemed “exercise in disguise” by instructors in both The Huffington Post and USA Today. The dance-fitness program—now a mainstay in thousands of gyms worldwide—syncs basic dance steps and calisthenics to upbeat music, often drawing upon Latin styles such as merengue, salsa, and flamenco. Certified instructors demonstrate each piece of choreography at the front of the room, motivating participants to groove at their own pace and add creative flairs as they see fit. The program currently branches off into eight variations, including Zumba Gold for senior citizens, Zumbatomic for children, and Zumba Toning for exercisers who wish to incorporate strength-training elements. Zumba got its start in Colombia in the mid-1990s, the brainchild of fitness instructor Alberto “Beto” Perez. According to Reuters, Beto initially wanted to name it Rumba—a Spanish word that can translate to party—but swapped in the Z when he found his first choice was trademarked. Today, Beto keeps up with the constantly changing musical culture by arranging new routines for his vast network of instructors every two months, incorporating newer styles such as hip-hop and reggaeton and enlisting artists such as Pitbull and Wyclef Jean to record Zumba-specific tracks.",
                "fine_print": "Limit 2 per person, may buy 1 additional as gift(s). Limit 1 per visit. New customers only. Valid only for option purchased.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1041264/click?api_key=WkXDXfXX",
                "price": 9.75,
                "value": 20,
                "discount_amount": 10.25,
                "discount_percentage": 0.5125,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1041264/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-06-11T00:00:00Z",
                "created_at": "2018-12-13T09:18:05Z",
                "updated_at": "2019-02-15T09:42:30Z",
                "merchant": {
                    "id": 306865,
                    "name": "Goza Dance Fitness",
                    "address": "13960 Westheimer Road",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77077",
                    "country": "US",
                    "latitude": 29.7357791,
                    "longitude": -95.6362589,
                    "phone_number": "+18329555182"
                }
            }
        },
        {
            "deal": {
                "id": 1172852,
                "title": "50% Off One Personal Training Session at Fitness 19 - Houston",
                "short_title": "50% Off One Personal Training Session",
                "description": "For $3, receive 50% Off One Personal Training Session. Worth $25 or more depending on your order. 50% off One $50 30 Minute Personal Training Session or 50% off One $90 60 Minute Personal Training Sesson",
                "fine_print": "Limit 1 per person, may buy 1 additional as gift. Promotional value paid will be auto-refunded after expiration. This voucher is issued by the merchant. Additional fees may apply.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1172852/click?api_key=WkXDXfXX",
                "price": 3,
                "value": 25,
                "discount_amount": 22,
                "discount_percentage": 0.88,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1172852/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-06-15T00:00:00Z",
                "created_at": "2019-02-15T09:42:30Z",
                "updated_at": "2019-02-15T09:42:30Z",
                "merchant": {
                    "id": 332695,
                    "name": "Fitness 19 - Houston",
                    "address": "17111 West Rd",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77095",
                    "country": "US",
                    "latitude": 29.9055747,
                    "longitude": -95.6705011,
                    "phone_number": "+12818550177"
                }
            }
        },
        {
            "deal": {
                "id": 1082278,
                "title": "Five or Ten Drop-In Kickboxing Workout at 9Round Fitness (Up to 81% Off)",
                "short_title": "Up to 81% Off Kickboxing Workout at 9Round Fitness",
                "description": "A 30-minute kickboxing workout combines interval, cardiovascular, and strength training sessions performed on nine challenging stations.",
                "fine_print": "Appointment required for first time users. Last class must be used within a month of first use. Limit 1 per person, may buy 2 additional as gift(s). May be repurchased every 90 days. Valid only for option purchased. All goods or services must be used by the same person.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1082278/click?api_key=WkXDXfXX",
                "price": 19,
                "value": 75,
                "discount_amount": 56,
                "discount_percentage": 0.7466666666666667,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Unkown",
                "category_slug": "unknown",
                "image_url": "https://api.discountapi.com/v2/deals/1082278/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-04-07T00:00:00Z",
                "created_at": "2019-01-07T09:18:54Z",
                "updated_at": "2019-01-12T09:53:20Z",
                "merchant": {
                    "id": 316625,
                    "name": "9Round Fitness",
                    "address": "15718 State Highway 288",
                    "locality": "Pearland",
                    "region": "TX",
                    "postal_code": "77584",
                    "country": "US",
                    "latitude": 29.569722,
                    "longitude": -95.3880252
                }
            }
        },
        {
            "deal": {
                "id": 1088995,
                "title": "One Month of Unlimited Group Cross-Training Classes at T3 Cross Training (Up to 70% Off) ",
                "short_title": "Up to 70% Off Unlimited Group Cross-Training Classes ",
                "description": "*$37 for one month unlimited group cross-training classes ($125 value) T3 What services does your business offer and what makes your business stand out from the competition? We offer Group Fitness Classes for all levels. We pride ourselves by only hiring passionate trained coaches who run, fun, safe, easy to learn workouts (HIIT) that will help burn the fat and lose the weight and give you your confidence back! What was the inspiration to start or run this business? After being a police officer for 15 years, and seeing a need in my fellow officers to be in better shape, I became a fitness coach and begin to train officers and citizens (at a local gym) to be the best versions of themselves they could be. What do you love most about your job? I love seeing people become who they want to be…fitter, better, healthier, and more confident. I love building relationships and enjoy when families workout together. What is the best reaction you’ve ever gotten from a customer? When a husband told me that I had help saved his life and his marriage! T3 Weight Loss and Fitness is about making people who normally don’t feel comfortable in a gym let along in a group fitness setting feel comfortable in their own body surrounded by caring, highly encouraging trained coaches who want nothing more than to see the results your want and Need! T3 Weight Loss and Fitness Class is about one thing….Losing weight and burning Fat with a one hour coach lead HIIT session that includes a warm-up workout cool down and stretch out. Nutritional and supplement coaching available as well.",
                "fine_print": "Appointment required. Limit 1 per person, may buy 1 additional as gift(s). New customers only. Valid only for option purchased. All goods or services must be used by the same person.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1088995/click?api_key=WkXDXfXX",
                "price": 37,
                "value": 125,
                "discount_amount": 88,
                "discount_percentage": 0.704,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1088995/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-04-10T00:00:00Z",
                "created_at": "2019-01-10T09:18:04Z",
                "updated_at": "2019-01-10T09:18:04Z",
                "merchant": {
                    "id": 317227,
                    "name": "T3",
                    "address": "12999 Murphy Road",
                    "locality": "Stafford",
                    "region": "TX",
                    "postal_code": "77477",
                    "country": "US",
                    "latitude": 29.6351599,
                    "longitude": -95.5631211,
                    "phone_number": "+18324496076"
                }
            }
        },
        {
            "deal": {
                "id": 1172898,
                "title": "5 or 10 Class Pass for Pilates at Aerobifit Fitness (Up to 67% Off)",
                "short_title": "Up to 67% Off Pilates at Aerobifit Fitness",
                "description": "Pilates classes build strength, creating a sleek and toned physique. It teaches body awareness, good posture and easy graceful movement, while improving flexibility and agility. View the class schedule",
                "fine_print": "Registration required. Limit 2 per person, may buy 1 additional as gift(s). Limit 1 per visit. Valid only for option purchased. Not valid for clients active within the past 6 month(s). All goods or services must be used by the same person.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1172898/click?api_key=WkXDXfXX",
                "price": 49,
                "value": 150,
                "discount_amount": 101,
                "discount_percentage": 0.6733333333333333,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Pilates",
                "category_slug": "pilates",
                "image_url": "https://api.discountapi.com/v2/deals/1172898/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-06-15T00:00:00Z",
                "created_at": "2019-02-15T09:42:31Z",
                "updated_at": "2019-02-15T09:42:31Z",
                "merchant": {
                    "id": 332708,
                    "name": "Aerobifit Fitness",
                    "address": "14090 Memorial Dr",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77079",
                    "country": "US",
                    "latitude": 29.7704764444,
                    "longitude": -95.5913307778,
                    "phone_number": "+12814973310"
                }
            }
        },
        {
            "deal": {
                "id": 1029871,
                "title": "Microdermabrasion or High-Frequency Facial with Optional Peel at MC Health Beauty Fitness(Up to 78% Off)",
                "short_title": "Up to 78% Off Facial at MC Health Beauty Fitness",
                "description": "Potential benefits: brighter and softer skin in the short term, meaning makeup can be applied more smoothly. After multiple treatments, you may notice a reduction in sunspots, scars, and fine lines, as well as improved skin tone and clarity. Learn more about microdermabrasion",
                "fine_print": "Appointment required. Limit 1 per person, may buy 1 additional as gift(s). May be repurchased every 90 days. Limit 1 per visit. All goods or services must be used by the same person. Merchant's standard cancellation policy applies (any fees not to exceed voucher price).",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1029871/click?api_key=WkXDXfXX",
                "price": 29,
                "value": 129,
                "discount_amount": 100,
                "discount_percentage": 0.7751937984496124,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Dermatology",
                "category_slug": "dermatology",
                "image_url": "https://api.discountapi.com/v2/deals/1029871/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-03-05T00:00:00Z",
                "created_at": "2018-12-05T09:17:48Z",
                "updated_at": "2019-01-12T09:53:01Z",
                "merchant": {
                    "id": 304735,
                    "name": "MC Health Beauty Fitness",
                    "address": "6250 Westpark Drive Suite #320",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77057",
                    "country": "US",
                    "latitude": 29.7241101,
                    "longitude": -95.49441329999999,
                    "phone_number": "+17138852659"
                }
            }
        },
        {
            "deal": {
                "id": 1093369,
                "title": "Deluxe Climbing Day Pass For One, Two, or Four at inSPIRE Rock (Up to 42% Off)",
                "short_title": "Up to 42% Off Deluxe Climbing Pass at inSPIRE Rock",
                "description": "Indoor What’s included: All-day climbing pass Shoes Harness Chalk Appropriate for skill levels: beginner to advanced Indoor Rock Climing FAQs What should I wear? Loose-fitting clothing that you can easily move around in. You’ll be able to grab climbing shoes, harness, and other necessary gear onsite. Do I have to be in good shape? Not really—climbing gyms have courses that cater to a wide range of fitness levels. Generally speaking, if you can climb a ladder you can indoor rock climb. What if I’m afraid of heights? Try bouldering, which takes place on shorter walls and doesn’t require harnesses or other top-rope gear.",
                "fine_print": "Valid only for location purchased. Entire voucher value must be used in one purchase. Must sign waiver. Limit 1 per person, may buy 1 additional as gift(s).",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1093369/click?api_key=WkXDXfXX",
                "price": 37,
                "value": 60,
                "discount_amount": 23,
                "discount_percentage": 0.38333333333333336,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Outdoor Adventures",
                "category_slug": "outdoor-adventures",
                "image_url": "https://api.discountapi.com/v2/deals/1093369/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-04-12T00:00:00Z",
                "created_at": "2019-01-12T09:53:16Z",
                "updated_at": "2019-01-12T09:53:16Z",
                "merchant": {
                    "id": 299058,
                    "name": "inSPIRE Rock",
                    "address": "403 East Louetta Road",
                    "locality": "Spring",
                    "region": "TX",
                    "postal_code": "77373",
                    "country": "US",
                    "latitude": 30.0696973,
                    "longitude": -95.42905379999999,
                    "phone_number": "+12812887625"
                }
            }
        },
        {
            "deal": {
                "id": 1207247,
                "title": "Two, Four, or Eight Laser-Lipo Sessions with Whole-Body Vibration at Slim Fit Body Contouring (Up to 57% Off)",
                "short_title": "Up to 57% Off Laser-Lipo Sessions at Slim Fit Body Contouring",
                "description": "Laser-Lipo: During the procedure, a licensed professional targets fat deposits using laser-emitting pads, causing the fat cells to perforate and disperse their contents. Eight sessions recommended; two sessions per week. Learn more about Laser Lipo: how it works and what to know before you go. Who’s eligible for laser lipo? Valid treatment areas: Abdomen Legs Back Arms Face Chin",
                "fine_print": "2 and 4 sessions should be used within one month of activation. 8 sessions should be used within two months of activation. Appointment required. Must sign waiver. Must use all treatments on same area. Consultation required; non-candidates and other refund requests will be honored before service provided. Limit 1 per person, may buy 1 additional as gift(s). May be repurchased every 30 days. Limit 1 per visit. Valid only for option purchased. All goods or services must be used by the same person. Merchant's standard cancellation policy applies (any fees not to exceed voucher price). 24-hour cancellation notice required.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1207247/click?api_key=WkXDXfXX",
                "price": 69,
                "value": 150,
                "discount_amount": 81,
                "discount_percentage": 0.54,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Health & Beauty",
                "category_slug": "health-beauty",
                "image_url": "https://api.discountapi.com/v2/deals/1207247/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-08-31T00:00:00Z",
                "created_at": "2019-03-04T09:28:41Z",
                "updated_at": "2019-03-04T09:28:41Z",
                "merchant": {
                    "id": 340110,
                    "name": "Slim Fit Body Contouring",
                    "address": "2855 Mangum Road",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77092",
                    "country": "US",
                    "latitude": 29.8137144,
                    "longitude": -95.45978029999999
                }
            }
        },
        {
            "deal": {
                "id": 1193693,
                "title": "$40 for $80 Worth of Services — DJ's Better Body Personal Fitness",
                "short_title": "50% Off Services",
                "description": "$80 Worth of Services",
                "fine_print": "Appointment required, same day appointments accepted. Limit 2 per person, may buy 2 additional as gift(s). May be repurchased every 30 days. Limit 1 per visit. New customers only. All goods or services must be used by the same person.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1193693/click?api_key=WkXDXfXX",
                "price": 40,
                "value": 80,
                "discount_amount": 40,
                "discount_percentage": 0.5,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1193693/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-06-25T00:00:00Z",
                "created_at": "2019-02-25T09:31:11Z",
                "updated_at": "2019-02-25T09:31:11Z",
                "merchant": {
                    "id": 336825,
                    "name": "DJs better body",
                    "address": "2500 East T C Jester Boulevard",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77008",
                    "country": "US",
                    "latitude": 29.8078885,
                    "longitude": -95.4366706,
                    "phone_number": "+17134096254"
                }
            }
        },
        {
            "deal": {
                "id": 1082275,
                "title": "Dance Classes at The Pole Experience (up to 48% Off). Three Options Available.",
                "short_title": "Up to 48% Off Dance Classes at The Pole Experience",
                "description": "Fun fitness classes designed for all-experience levels",
                "fine_print": "Limit 1 per person, may buy 1 additional as gift(s). Limit 1 per visit. Not valid for clients active within the past 6 month(s). Valid for all dance class options. Registration required. Valid only for option purchased. All goods or services must be used by the same person.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1082275/click?api_key=WkXDXfXX",
                "price": 39,
                "value": 75,
                "discount_amount": 36,
                "discount_percentage": 0.48,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1082275/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-04-07T00:00:00Z",
                "created_at": "2019-01-07T09:18:54Z",
                "updated_at": "2019-01-12T09:53:20Z",
                "merchant": {
                    "id": 94816,
                    "name": "The Pole Experience",
                    "address": "2702 McGowen Street",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77004",
                    "country": "US",
                    "latitude": 29.7364424,
                    "longitude": -95.3594757,
                    "phone_number": "+12817838847",
                    "url": "https://www.facebook.com/ThePoleExperience"
                }
            }
        },
        {
            "deal": {
                "id": 1202219,
                "title": "Three or Four Introductory Trial Sessions for Beginners Group Exercise at Creative Workouts (Up to 92% Off)",
                "short_title": "Up to 92% Off Beginners Group Exercise at Creative Workouts",
                "description": "Fitness classes offer a full-body workout, which can help students tone, tighten, lose inches, and build strength View the class schedule",
                "fine_print": "Appointment required. Limit 1 per person, may buy 1 additional as gift(s). May be repurchased every 180 days. Limit 1 per visit. Valid only for option purchased. All goods or services must be used by the same person.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1202219/click?api_key=WkXDXfXX",
                "price": 5,
                "value": 60,
                "discount_amount": 55,
                "discount_percentage": 0.9166666666666666,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1202219/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-06-29T00:00:00Z",
                "created_at": "2019-03-01T09:27:44Z",
                "updated_at": "2019-03-01T09:27:44Z",
                "merchant": {
                    "id": 94793,
                    "name": "Creative Workouts",
                    "address": "3505 South Dairy Ashford Road",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77082",
                    "country": "US",
                    "latitude": 29.7227345,
                    "longitude": -95.6042009,
                    "phone_number": "+12817165371",
                    "url": "http://www.creative-workouts.com"
                }
            }
        },
        {
            "deal": {
                "id": 405001,
                "title": "Nevaeh's Plate",
                "short_title": "Nevaeh's Plate",
                "description": "A wonderful party will live on in your memory. That's why we not only offer a multifaceted menu as a party service for Houston and the surrounding area, but we also provide the organizational talent, wait staff and equipment for a flawless event. Whether a family celebration at home or a large event in a rented location, our experienced team has the talent to make your celebration an unforgettable experience. We also provide personal chef, delivery, and take out services to fit the needs of each customer.",
                "fine_print": "Minimum purchase of $50 at restaurant.",
                "url": "https://api.discountapi.com/v2/deals/405001/click?api_key=WkXDXfXX",
                "price": 10,
                "value": 25,
                "discount_amount": 15,
                "discount_percentage": 0.6,
                "provider_name": "Restaurant.com",
                "provider_slug": "restaurant-com",
                "category_name": "Restaurants",
                "category_slug": "restaurants",
                "image_url": "https://api.discountapi.com/v2/deals/405001/image?api_key=WkXDXfXX",
                "online": false,
                "created_at": "2018-03-20T20:08:20Z",
                "updated_at": "2018-11-19T08:23:45Z",
                "merchant": {
                    "id": 194388,
                    "name": "Nevaeh's Plate",
                    "address": "",
                    "region": "",
                    "country": "US",
                    "latitude": 29.71712,
                    "longitude": -95.60967
                }
            }
        },
        {
            "deal": {
                "id": 1023437,
                "title": "First-Visit Indoor Rock-Climbing ",
                "short_title": "Up to 55% Off First-Visit Packages at Climb Woodlands",
                "description": "Indoor climbing What’s included: First-Visit Package for Children 4-10 Day pass Shoes Chalk First-Visit Package for Adults Day pass Shoes Chalk Belay Course Indoor Rock Climing FAQs Is it safe? Yes. Rock climbing gyms typically require a safety course on proper belaying techniques, knots, and other fundamentals for top-rope courses and have designated “beginner” courses for first timers. What should I wear? Loose-fitting clothing that you can easily move around in. You’ll be able to grab climbing shoes, harness, and other necessary gear onsite. Do I have to be in good shape? Not really—climbing gyms have courses that cater to a wide range of fitness levels. Generally speaking, if you can climb a ladder you can indoor rock climb. What if I’m afraid of heights? Try bouldering, which takes place on shorter walls and doesn’t require harnesses or other top-rope gear. Bouldering focuses more on moving sideways than vertically, so climbers rarely get more than 10–12 feet off the ground.",
                "fine_print": "Punch pass may be shared by multiple guests. All options include harness. Must sign waiver. Younger than 18 must have guardian-signed waiver. Younger than 13 must be accompanied by guardian. Limit 1 per person, may buy 2 additional as gift(s). New customers only. Valid only for option purchased. Not valid with other offers or promotions.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1023437/click?api_key=WkXDXfXX",
                "price": 15,
                "value": 30,
                "discount_amount": 15,
                "discount_percentage": 0.5,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Outdoor Adventures",
                "category_slug": "outdoor-adventures",
                "image_url": "https://api.discountapi.com/v2/deals/1023437/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-03-31T00:00:00Z",
                "created_at": "2018-12-01T09:17:22Z",
                "updated_at": "2018-12-01T09:17:22Z",
                "merchant": {
                    "id": 94791,
                    "name": "Climb Woodlands",
                    "address": "7515 Oak Bluff Drive",
                    "locality": "Magnolia",
                    "region": "TX",
                    "postal_code": "77354",
                    "country": "US",
                    "latitude": 30.2152026,
                    "longitude": -95.5829361,
                    "phone_number": "+18325213131",
                    "url": "https://climbwoodlands.com/"
                }
            }
        },
        {
            "deal": {
                "id": 1172900,
                "title": "Ten Yoga, Mat Pilates, or Barre Classes or One-Month Unlimited at Pure Balance (Up to 73% Off)",
                "short_title": "Up to 73% Off Fitness Classes at Pure Balance",
                "description": "In the Yoga, Mat Pilates, and Barre classes students can not only improve their fitness level, but also the overall well-being View the class schedule About the instructors: certified instructors",
                "fine_print": "Registration required. Limit 1 per person, may buy 2 additional as gift(s). Limit 1 per visit. Valid only for option purchased. Not valid for clients active within the past 6 month(s). All goods or services must be used by the same person.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1172900/click?api_key=WkXDXfXX",
                "price": 49,
                "value": 180,
                "discount_amount": 131,
                "discount_percentage": 0.7277777777777777,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1172900/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-06-15T00:00:00Z",
                "created_at": "2019-02-15T09:42:31Z",
                "updated_at": "2019-02-15T09:42:31Z",
                "merchant": {
                    "id": 332709,
                    "name": "Pure Balance",
                    "address": "13040 Louetta Rd. #228",
                    "locality": "Cypress",
                    "region": "TX",
                    "postal_code": "77429",
                    "country": "US",
                    "latitude": 29.9962566,
                    "longitude": -95.6211276,
                    "phone_number": "+12812514400"
                }
            }
        },
        {
            "deal": {
                "id": 1179058,
                "title": "Two or Four Saturday Outdoor Boot Camp Classes at TX Fit Outdoor Bootcamp with Atarhe Clarke (Up to 69% Off)",
                "short_title": "Up to 69% Off at TX Fit Outdoor Bootcamp with Atarhe Clarke",
                "description": "Boot camp classes consist of dynamic stretching and running, followed by a wide variety of interval training, including lifting weights, pulling rubber TRX straps, pushups, situps, and more.",
                "fine_print": "Limit 1 per person, may buy 2 additional as gift(s). Limit 1 per visit. May be repurchased every 180 days. Please call Ashley to schedule 678-956-0180 or go in the company website and sign up for classes.",
                "number_sold": 0,
                "url": "https://api.discountapi.com/v2/deals/1179058/click?api_key=WkXDXfXX",
                "price": 19,
                "value": 40,
                "discount_amount": 21,
                "discount_percentage": 0.525,
                "provider_name": "Groupon",
                "provider_slug": "groupon",
                "category_name": "Fitness Classes",
                "category_slug": "fitness-classes",
                "image_url": "https://api.discountapi.com/v2/deals/1179058/image?api_key=WkXDXfXX",
                "online": false,
                "expires_at": "2019-06-16T00:00:00Z",
                "created_at": "2019-02-16T09:33:59Z",
                "updated_at": "2019-02-16T09:33:59Z",
                "merchant": {
                    "id": 333691,
                    "name": "TXFit Outdoor Bootcamp with Atarhe Clarke",
                    "address": "6201 Hermann Park Dr",
                    "locality": "Houston",
                    "region": "TX",
                    "postal_code": "77030",
                    "country": "US",
                    "latitude": 29.718298,
                    "longitude": -95.390942,
                    "phone_number": "+17138940401"
                }
            }
        }
    ]
}