houston_shoes = {
  "query": {
      "total": 9,
      "page": 1,
      "per_page": 20,
      "query": "shoes",
      "location": {
          "latitude": 29.7604,
          "longitude": -95.3698
      },
      "radius": 50,
      "online": null,
      "category_slugs": null,
      "provider_slugs": null,
      "updated_after": null,
      "order": null
  },
  "deals": [
      {
          "deal": {
              "id": 1196924,
              "title": "Two Hours of Bowling and Shoe Rentals for Two, Four, or Six Guests at Bowlmor Lanes and Bowlero (Up to 57% Off)",
              "short_title": "Up to 57% Off Two Hours of Bowling and Shoe Rentals",
              "description": "Two Hours of Bowling and Shoe Rentals Choose between two-, four-, or six-person options Each voucher good for one lane Includes shoe rentals for each guest Gather friends or take a date to this upscale bowling alley About Bowlmor Lanes and Bowlero Bowlmor Lanes and Bowlero takes bowling to the next level with their state-of-the-art arcade, multi-player laser tag. and epic eats. Each location features bowling lanes decked out with black lights, plush lounge seats, and HD video walls. Here the menu is nationally-recognized and comes stuffed with everything from oversized share-ables to classic burgers and sandwiches each with their own spin. Come enjoy a game of bowling and stay for the featured bites, games, and alluring visuals. Click to explore all Bowlmor Lanes and Bowlero have to offer.",
              "fine_print": "All sales final. Not valid until 24 hours after purchase. Advanced reservations not available; subject to availability. Call in advance to confirm availability. Not valid Saturdays after 6 p.m. Not valid for contracted group events, birthdays, leagues or tournaments. Cannot be combined with other offers. Must use promotional value in 1 visit. Voucher is valid for one lane per 2-, 4-, or 6-person group. Valid only at listed locations. Limit 2 per person, may buy 2 additional as gift(s).",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/1196924/click?api_key=WkXDXfXX",
              "price": 28,
              "value": 60.28,
              "discount_amount": 32.28,
              "discount_percentage": 0.53550099535501,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Unkown",
              "category_slug": "unknown",
              "image_url": "https://api.discountapi.com/v2/deals/1196924/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-06-07T04:59:59Z",
              "created_at": "2019-02-27T09:25:13Z",
              "updated_at": "2019-02-27T09:25:13Z",
              "merchant": {
                  "id": 235612,
                  "name": "Bowlmor Lanes and Bowlero",
                  "address": "925 Bunker Hill Road",
                  "locality": "Houston",
                  "region": "TX",
                  "postal_code": "77024",
                  "country": "US",
                  "latitude": 29.7802586,
                  "longitude": -95.5322836
              }
          }
      },
      {
          "deal": {
              "id": 1029873,
              "title": "Annual Pass or Bowling with Shoes, Buffet, Drinks, and Video Game at iT'Z Family, Food and Fun (Up to 50% Off)",
              "short_title": "Up to 50% Off Annual Pass or Bowling Packages",
              "description": "Choice of: Unlimited Visits Annual Pass for One Person Unlimited Visits Annual Pass for Two People Unlimited Visits Annual Pass for Four People One-Hour Bowling with Shoe Rental, Buffet, Drinks, and All-Day Unlimited Video Games for Two One-Hour Bowling with Shoe Rental, Buffet, Drinks, and All-Day Unlimited Video Games for Four Unlimited Visits Annual Pass includes, per person: Valid from 12/1/18 through 12/31/19 Unlimited buffet and drinks Unlimited access to attractions One game of bowling per visit Unlimited video games (does not include redemption tickets, coin action, or prize games) The all-you-can-eat buffet includes pizza, pasta, a salad bar, a potato bar, plenty of desserts, and unlimited fountain beverages, coffee, and tea. Unlimited video game play is good for all games that do not give out tickets or prizes.",
              "fine_print": "All day unlimited video games not valid for games that give tickets or prizes. Any additional guests must purchase buffet for entry. Buffet closes at 8 p.m. No reservations. Subject to availability. Limit 2 per person, may buy 1 additional as gift(s). Valid only for option purchased. Valid only at listed locations.",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/1029873/click?api_key=WkXDXfXX",
              "price": 85,
              "value": 99.99,
              "discount_amount": 14.989999999999995,
              "discount_percentage": 0.14991499149914986,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Unkown",
              "category_slug": "unknown",
              "image_url": "https://api.discountapi.com/v2/deals/1029873/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-03-05T00:00:00Z",
              "created_at": "2018-12-05T09:18:21Z",
              "updated_at": "2018-12-05T09:18:21Z",
              "merchant": {
                  "id": 228017,
                  "name": "iT'Z- Pasadena",
                  "address": "5950 Fairmont Parkway",
                  "locality": "Pasadena",
                  "region": "TX",
                  "postal_code": "77505",
                  "country": "US",
                  "latitude": 29.6493929,
                  "longitude": -95.1501026,
                  "phone_number": "+12819982424"
              }
          }
      },
      {
          "deal": {
              "id": 1023437,
              "title": "First-Visit Indoor Rock-Climbing ",
              "short_title": "Up to 55% Off First-Visit Packages at Climb Woodlands",
              "description": "Indoor climbing What’s included: First-Visit Package for Children 4-10 Day pass Shoes Chalk First-Visit Package for Adults Day pass Shoes Chalk Belay Course Indoor Rock Climing FAQs Is it safe? Yes. Rock climbing gyms typically require a safety course on proper belaying techniques, knots, and other fundamentals for top-rope courses and have designated “beginner” courses for first timers. What should I wear? Loose-fitting clothing that you can easily move around in. You’ll be able to grab climbing shoes, harness, and other necessary gear onsite. Do I have to be in good shape? Not really—climbing gyms have courses that cater to a wide range of fitness levels. Generally speaking, if you can climb a ladder you can indoor rock climb. What if I’m afraid of heights? Try bouldering, which takes place on shorter walls and doesn’t require harnesses or other top-rope gear. Bouldering focuses more on moving sideways than vertically, so climbers rarely get more than 10–12 feet off the ground.",
              "fine_print": "Punch pass may be shared by multiple guests. All options include harness. Must sign waiver. Younger than 18 must have guardian-signed waiver. Younger than 13 must be accompanied by guardian. Limit 1 per person, may buy 2 additional as gift(s). New customers only. Valid only for option purchased. Not valid with other offers or promotions.",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/1023437/click?api_key=WkXDXfXX",
              "price": 15,
              "value": 30,
              "discount_amount": 15,
              "discount_percentage": 0.5,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Outdoor Adventures",
              "category_slug": "outdoor-adventures",
              "image_url": "https://api.discountapi.com/v2/deals/1023437/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-03-31T00:00:00Z",
              "created_at": "2018-12-01T09:17:22Z",
              "updated_at": "2018-12-01T09:17:22Z",
              "merchant": {
                  "id": 94791,
                  "name": "Climb Woodlands",
                  "address": "7515 Oak Bluff Drive",
                  "locality": "Magnolia",
                  "region": "TX",
                  "postal_code": "77354",
                  "country": "US",
                  "latitude": 30.2152026,
                  "longitude": -95.5829361,
                  "phone_number": "+18325213131",
                  "url": "https://climbwoodlands.com/"
              }
          }
      },
      {
          "deal": {
              "id": 1093369,
              "title": "Deluxe Climbing Day Pass For One, Two, or Four at inSPIRE Rock (Up to 42% Off)",
              "short_title": "Up to 42% Off Deluxe Climbing Pass at inSPIRE Rock",
              "description": "Indoor What’s included: All-day climbing pass Shoes Harness Chalk Appropriate for skill levels: beginner to advanced Indoor Rock Climing FAQs What should I wear? Loose-fitting clothing that you can easily move around in. You’ll be able to grab climbing shoes, harness, and other necessary gear onsite. Do I have to be in good shape? Not really—climbing gyms have courses that cater to a wide range of fitness levels. Generally speaking, if you can climb a ladder you can indoor rock climb. What if I’m afraid of heights? Try bouldering, which takes place on shorter walls and doesn’t require harnesses or other top-rope gear.",
              "fine_print": "Valid only for location purchased. Entire voucher value must be used in one purchase. Must sign waiver. Limit 1 per person, may buy 1 additional as gift(s).",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/1093369/click?api_key=WkXDXfXX",
              "price": 37,
              "value": 60,
              "discount_amount": 23,
              "discount_percentage": 0.38333333333333336,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Outdoor Adventures",
              "category_slug": "outdoor-adventures",
              "image_url": "https://api.discountapi.com/v2/deals/1093369/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-04-12T00:00:00Z",
              "created_at": "2019-01-12T09:53:16Z",
              "updated_at": "2019-01-12T09:53:16Z",
              "merchant": {
                  "id": 299058,
                  "name": "inSPIRE Rock",
                  "address": "403 East Louetta Road",
                  "locality": "Spring",
                  "region": "TX",
                  "postal_code": "77373",
                  "country": "US",
                  "latitude": 30.0696973,
                  "longitude": -95.42905379999999,
                  "phone_number": "+12812887625"
              }
          }
      },
      {
          "deal": {
              "id": 1029876,
              "title": "Bowling Package for Two or Four or Unlimited Annual Pass at iT'Z (Up to 50% Off)",
              "short_title": "Up to 50% Off Bowling Packages at iT'Z",
              "description": "Choice of: Unlimited Visits Annual Pass for One Unlimited Visits Annual Pass for Two Unlimited Visits Annual Pass for Four One-Hour Bowling with Shoe Rental, Buffet, Drinks, and All-Day Unlimited Video Games for Two One-Hour Bowling with Shoe Rental, Buffet, Drinks, and All-Day Unlimited Video Games for Four Unlimited visits annual pass includes, per person: Valid 12/1/18–12/31/19 Unlimited buffet and drinks Unlimited video games Unlimited attractions One game of bowling per visit The all-you-can-eat buffet includes pizza, pasta, a salad bar, a potato bar, plenty of desserts, and unlimited fountain beverages, coffee, and tea. Unlimited video game play is good for all games that do not give out tickets or prizes.",
              "fine_print": "All day unlimited video games not valid for games that give tickets or prizes. Any additional guests must purchase buffet for entry. Buffet closes at 8 p.m. No reservations. Subject to availability. Limit 2 per person, may buy 1 additional as gift(s). Valid only for option purchased. Valid only at listed locations.",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/1029876/click?api_key=WkXDXfXX",
              "price": 85,
              "value": 99.99,
              "discount_amount": 14.989999999999995,
              "discount_percentage": 0.14991499149914986,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Unkown",
              "category_slug": "unknown",
              "image_url": "https://api.discountapi.com/v2/deals/1029876/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-03-05T00:00:00Z",
              "created_at": "2018-12-05T09:18:21Z",
              "updated_at": "2018-12-05T09:18:21Z",
              "merchant": {
                  "id": 228018,
                  "name": "iT'Z- Willowbrook",
                  "address": "18355 Tomball Parkway",
                  "locality": "Houston",
                  "region": "TX",
                  "postal_code": "77070",
                  "country": "US",
                  "latitude": 29.9641587,
                  "longitude": -95.5551087,
                  "phone_number": "+18326782151"
              }
          }
      },
      {
          "deal": {
              "id": 1174948,
              "title": "Bead Making Class for One or Two People at Juggernaut Glass (Up to 50% Off)",
              "short_title": "Up to 50% Off Bead Making Class at Juggernaut Glass",
              "description": "Choice of: Two-Hour Glass Bead Making Class for One Person Two-Hour Glass Bead Making Class for Two People See the schedule.",
              "fine_print": "Limit 3 per person, may buy 1 additional as gift. Valid only for option purchased. Must be 18 or older with valid ID. Registration required, two weeks notice required. Customers must wear close-toed shoes. Customers must make arrangements to pick up glassworks following class.",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/1174948/click?api_key=WkXDXfXX",
              "price": 79,
              "value": 125,
              "discount_amount": 46,
              "discount_percentage": 0.368,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Life Skills Classes",
              "category_slug": "life-skills-classes",
              "image_url": "https://api.discountapi.com/v2/deals/1174948/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-06-15T00:00:00Z",
              "created_at": "2019-02-15T11:28:32Z",
              "updated_at": "2019-02-15T11:28:32Z",
              "merchant": {
                  "id": 333258,
                  "name": "Juggernaut Glass",
                  "address": "214 East 27th Street",
                  "locality": "Houston",
                  "region": "TX",
                  "postal_code": "77008",
                  "country": "US",
                  "latitude": 29.8110677,
                  "longitude": -95.3969205,
                  "phone_number": "+18323788842"
              }
          }
      },
      {
          "deal": {
              "id": 1187594,
              "title": "One- or Two-Month Gym Membership with Fitness Consultation and Personal-Training Session at Snap Fitness (Up to 96% Off)",
              "short_title": "Up to 96% Off Gym Membership to Snap Fitness",
              "description": "A good workout regimen provides the courage needed to march back into the office, take the clown nose off, and demand a smaller, funnier car. Fill oversize shoes with self-confidence with this voucher. Choose Between Two Options $8 for a one-month gym membership with a fitness consultation and one personal-training session (a $184.95 value) $19.50 for a two-month gym membership with a fitness consultation and one personal-training session (a $219.90 value) Snap Fitness facilitates workouts 24 hours a day with a repertoire of Cybex treadmills, weight machines, and free weights. Each membership begins with a personal-training session, during which a skilled fitness instructor conducts an assessment that includes BMI monitoring and suggestions for a weight-loss plan that doesn’t include bribing gravity.",
              "fine_print": "Must activate at Pearland location by expiration date on your voucher. Under 18 requires parent or legal guardian consent. Must sign waiver. Limit 1 per person, may buy 1 additional as gift(s). New customers only. Valid only for option purchased. Must be 18 or older.",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/1187594/click?api_key=WkXDXfXX",
              "price": 19.5,
              "value": 219.9,
              "discount_amount": 200.4,
              "discount_percentage": 0.9113233287858117,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Fitness Classes",
              "category_slug": "fitness-classes",
              "image_url": "https://api.discountapi.com/v2/deals/1187594/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-06-20T00:00:00Z",
              "created_at": "2019-02-20T09:31:14Z",
              "updated_at": "2019-02-20T09:31:14Z",
              "merchant": {
                  "id": 290285,
                  "name": "Snap Fitness",
                  "address": "3108 Dixie Farm Rd.",
                  "locality": "Pearland",
                  "region": "TX",
                  "postal_code": "77581",
                  "country": "US",
                  "latitude": 29.5484422,
                  "longitude": -95.2317125,
                  "phone_number": "+12819969800"
              }
          }
      },
      {
          "deal": {
              "id": 871013,
              "title": "$59 for Boudoir Photo Shoot with Three Outfits and One Digital Download ($130 Value)",
              "short_title": "55%  Off Boudoir Photo Shoot",
              "description": "The Deal $59 for a boudoir photo shoot with three outfits and one digital download ($130 value) Upon arrival, guests are greeted by the all-female staff and handed a glass of champagne or wine before browsing a wide selection of lingerie, jewelry, and shoes to create three different outfits. Clients can also bring their own outfits to use during the shoot. After choosing the outfits, the staff will help pick three different sets as the backdrops for the shoot and conceptualize a photo shoot with guests to create a unique and personalize session. Clients can come with their hair and makeup already done, or the staff can style client’s hair and makeup for an additional fee. The photographer captures clients in a variety of poses that the staff demonstrate for guests. Once the session is completed, an appointment is made, usually within a week, to come back to the studio to view the edited photos or check them out online. At the viewing appointment, clients meet with a staff member to go over the photographs. One digital download is included, however many other packages and printing options are available for an additional fee.",
              "fine_print": "Subject to availability. Appointment required. Limit 1 per person, may buy 1 additional as gift(s). Must use promotional value in 1 visit(s). Valid only for option purchased. All goods or services must be used by the same person. May be repurchased every 30 days. Must be 18 or older. Merchant's standard cancellation policy applies (any fees not to exceed voucher price).",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/871013/click?api_key=WkXDXfXX",
              "price": 59,
              "value": 130,
              "discount_amount": 71,
              "discount_percentage": 0.5461538461538461,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Photography Services",
              "category_slug": "photography-services",
              "image_url": "https://api.discountapi.com/v2/deals/871013/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-04-15T00:00:00Z",
              "created_at": "2018-10-17T10:09:47Z",
              "updated_at": "2019-01-12T10:35:32Z",
              "merchant": {
                  "id": 285751,
                  "name": "Bad Kitty Photography",
                  "address": "3410 Lousiana Street",
                  "locality": "Houston",
                  "region": "TX",
                  "postal_code": "77002",
                  "country": "US",
                  "latitude": 29.7417923,
                  "longitude": -95.38107269999999
              }
          }
      },
      {
          "deal": {
              "id": 1181664,
              "title": "The Moonlight Dolls Presents: Bitches Who Brunch",
              "short_title": "The Moonlight Dolls Presents: Bitches Who Brunch",
              "description": "Sunday brunch has never been so glam. Grab your girlfriends and a mimosa (or three) for Bitches Who Brunch, a first-class yet relaxing afternoon of music, comedy and show-stopping striptease featuring the world-famous Moonlight Dolls. You'll be dazzled by the Dolls' signature pop-up style that promises a one-of-a-kind weekend thrill. Host Abby Cadabra (Winner - Best Tease, San Antonio Burlesque Festival) leads the glittering troupe through electrifying aerial acts (keep your eyes peeled for the gorgeous, gravity-defying Ariel Airheart) and sizzling dance numbers. For additional purchase, you can dine on classic brunch fare like French Toast & Fried Chicken in Houston's elegant and sunny Prohibition Supperclub & Bar. Cap your weekend with the yummy cocktails, delectable brunch and pastie-perfect production of The Moonlight Dolls Presents: Bitches Who Brunch.The tickets identified in this promotion are made available through Goldstar. Groupon is not affiliated with or sponsored by Prohibition Theatre in connection with this deal. This offer is not eligible for promo codes.",
              "fine_print": "ALL SALES FINAL. Athletic wear, tennis shoes, excessively baggy clothing, and baseball caps will not be permitted in the theatre regardless of ticket purchase. Photography is not permitted in the theater. You must be age 21 or older to attend. A $32 brunch buffet is required, payable after the show. Groupon promo codes may not be used for this offer. Discount reflects current ticket prices, which may change. Ticket value includes all fees. Holder assumes all risk in connection with the event and releases Groupon, Goldstar, the venue and their affiliates from any related claims. Merchant is solely responsible to purchasers for the care and quality of the advertised goods and services.",
              "number_sold": 0,
              "url": "https://api.discountapi.com/v2/deals/1181664/click?api_key=WkXDXfXX",
              "price": 8,
              "value": 30,
              "discount_amount": 22,
              "discount_percentage": 0.7333333333333333,
              "provider_name": "Groupon",
              "provider_slug": "groupon",
              "category_name": "Life Skills Classes",
              "category_slug": "life-skills-classes",
              "image_url": "https://api.discountapi.com/v2/deals/1181664/image?api_key=WkXDXfXX",
              "online": false,
              "expires_at": "2019-03-10T16:00:00Z",
              "created_at": "2019-02-17T09:42:39Z",
              "updated_at": "2019-02-17T09:42:39Z",
              "merchant": {
                  "id": 270586,
                  "name": "Prohibition Theatre",
                  "address": "1008 Prairie Street",
                  "locality": "Houston",
                  "region": "TX",
                  "postal_code": "77002",
                  "country": "US",
                  "latitude": 29.7601,
                  "longitude": -95.3614085,
                  "phone_number": "+12819404636"
              }
          }
      }
  ]
}